/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerUidRouteImport } from './routes/seller.$uid'
import { Route as BookIdRouteImport } from './routes/book.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerUidRoute = SellerUidRouteImport.update({
  id: '/seller/$uid',
  path: '/seller/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/my-listings': typeof MyListingsRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/wishlist': typeof WishlistRoute
  '/book/$id': typeof BookIdRoute
  '/seller/$uid': typeof SellerUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/my-listings': typeof MyListingsRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/wishlist': typeof WishlistRoute
  '/book/$id': typeof BookIdRoute
  '/seller/$uid': typeof SellerUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/my-listings': typeof MyListingsRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/sell': typeof SellRoute
  '/wishlist': typeof WishlistRoute
  '/book/$id': typeof BookIdRoute
  '/seller/$uid': typeof SellerUidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/login'
    | '/my-listings'
    | '/notifications'
    | '/offers'
    | '/profile'
    | '/sell'
    | '/wishlist'
    | '/book/$id'
    | '/seller/$uid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/login'
    | '/my-listings'
    | '/notifications'
    | '/offers'
    | '/profile'
    | '/sell'
    | '/wishlist'
    | '/book/$id'
    | '/seller/$uid'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/login'
    | '/my-listings'
    | '/notifications'
    | '/offers'
    | '/profile'
    | '/sell'
    | '/wishlist'
    | '/book/$id'
    | '/seller/$uid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BrowseRoute: typeof BrowseRoute
  LoginRoute: typeof LoginRoute
  MyListingsRoute: typeof MyListingsRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  ProfileRoute: typeof ProfileRoute
  SellRoute: typeof SellRoute
  WishlistRoute: typeof WishlistRoute
  BookIdRoute: typeof BookIdRoute
  SellerUidRoute: typeof SellerUidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$uid': {
      id: '/seller/$uid'
      path: '/seller/$uid'
      fullPath: '/seller/$uid'
      preLoaderRoute: typeof SellerUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BrowseRoute: BrowseRoute,
  LoginRoute: LoginRoute,
  MyListingsRoute: MyListingsRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  ProfileRoute: ProfileRoute,
  SellRoute: SellRoute,
  WishlistRoute: WishlistRoute,
  BookIdRoute: BookIdRoute,
  SellerUidRoute: SellerUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
